# Generated by Django 3.1.8 on 2021-05-02 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('shops', '0002_auto_20210424_0041'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('vendor', models.CharField(choices=[('taxcom', 'TaxCom')], db_index=True, max_length=10, verbose_name='Vendor')),
                ('remote_id', models.CharField(db_index=True, max_length=36, verbose_name='Remote id')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Receipt number')),
                ('shift', models.PositiveIntegerField(blank=True, null=True, verbose_name='Shift')),
                ('cashier', models.CharField(blank=True, max_length=255, verbose_name='Cashier')),
                ('created_in_receipt', models.DateTimeField(blank=True, null=True, verbose_name='Created in receipt')),
                ('sum', models.FloatField(verbose_name='Sum')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ('created',),
                'unique_together': {('vendor', 'remote_id')},
                'index_together': {('vendor', 'remote_id')},
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('price', models.FloatField(verbose_name='Price')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('sum', models.FloatField(verbose_name='Sum')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='items.item')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='receipts.receipt')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ('order',),
            },
        ),
    ]
