# Generated by Django 3.1.8 on 2021-05-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20210424_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
