# Generated by Django 3.1.8 on 2021-05-10 15:49

from django.db import migrations, models


DEFAULT_RULES = (
    ("Россия, ", ""),
    ("Новосибирская обл., г. Новосибирск", "Новосибирск"),
    ("----------------------------------------", ""),
)


def create_default_rules(apps, schema_editor):
    ReplaceAddressRule = apps.get_model("shops", "ReplaceAddressRule")
    for old_text, new_text in DEFAULT_RULES:
        ReplaceAddressRule.objects.get_or_create(
            old_text=old_text, defaults={"new_text": new_text}
        )


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_shop_is_removed"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplaceAddressRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_text",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Old text"
                    ),
                ),
                (
                    "new_text",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="New text"
                    ),
                ),
            ],
            options={
                "verbose_name": "Replace address rule",
                "verbose_name_plural": "Replace address rules",
            },
        ),
        migrations.RunPython(create_default_rules, reverse_code=migrations.RunPython.noop),
    ]
