# Generated by Django 3.1.8 on 2021-05-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='General name')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Sub name')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='items.item')),
            ],
            options={
                'verbose_name': 'Item sub name',
                'verbose_name_plural': 'Item sub names',
                'ordering': ('name',),
            },
        ),
    ]
